### ISSUE TITLE
[Question] Enchantments

### ISSUE THREAD

**Issue by Nekkok** [diamonddevv/enderism#1]
What does each enchantment do? I can't find their descriptions anywhere and I think putting them on the description main page would help other players. Thank you for your work : )

**Comment by diamonddevv** [comment]
oh, sorry i didnt get back to you sooner!
here's a list of what they do:

Upthrust (Elytra): allows you to jump variably higher. The height at which you can jump decreases the more you jump, resetting when you stop and walk normally for about 5-10 ticks.
Velocity Protection (Elytra): Reduces damage taken from flying into things
Curse of Shackling (Elytra): Prevents the Elytra from opening.

Hope this helps, and feel free to ask any other questions! I will also add Enchantment Descriptions in game, and I really should get round to documenting things :)
