### ISSUE TITLE
incompat with things mod

### ISSUE THREAD

**Issue by jitterdev** [diamonddevv/enderism#3]
https://bytebin.lucko.me/twIOpopNVt enderism is not mentioned directly in the stack trace, but when i removed enderism, the mixin failure was no longer present sooo

**Comment by diamonddevv** [comment]
ill have a proper look at this later, but this looks to be some other mod using redirects. tldr; redirects can't be used by two mods. as far as i remember, enderism doesn't use any, but the exact cause is hard to easily pinpoint. ill have a look into this.

**Comment by jitterdev** [comment]
@diamonddevv
these are the conflictions. just do a wrap operation on yours
https://github.com/diamonddevv/enderism/blob/bb654838c5360265fbb198a819999b5ebc11dc3e/src/main/java/dev/diamond/enderism/mixin/LivingEntityMixin.java#L165
https://github.com/wisp-forest/things/blob/1.20.3/src/main/java/com/glisco/things/mixin/LivingEntityMixin.java#L54

**Comment by diamonddevv** [comment]
thank you so much! I can't even remember writing that mixin. i think i might have been confused haha, implementing a fix soon

<3

**Comment by diamonddevv** [comment]
Fixed in upcoming commit, thank you!
